# Generated by Django 4.0.5 on 2022-07-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True),
        ),
    ]
