# Generated by Django 4.0.5 on 2022-07-14 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_order_number', models.CharField(default=None, max_length=20)),
                ('setter_fname', models.CharField(blank=True, max_length=250)),
                ('setter_lname', models.CharField(blank=True, max_length=250)),
                ('setter_email', models.EmailField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('order_total', models.FloatField()),
                ('is_memoed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
